### ISSUE TITLE
Не работает выпадайка "О клубе"

### ISSUE THREAD

**Issue by misterspelik** [dlyapun/romantic#17]
В главном меню на самом верху в выпадайке "О клубе" нет ничего, хотя должно быть.

**Comment by Maksaft** [comment]
плюс внизу есть ссылка "о клубе"
http://tkr.od.ua/about/
пустая страница

**Comment by Maksaft** [comment]
Внизу всё ещё можно нажать на "о клубе" и выкинет на пустую страницу
![image](https://cloud.githubusercontent.com/assets/15012936/14702786/f5a99e46-07b4-11e6-8f17-19817e7a7874.png)
![image](https://cloud.githubusercontent.com/assets/15012936/14702793/0066ec44-07b5-11e6-9bde-b130828693d0.png)
