### ISSUE TITLE
не работает вкладка "контакты"

### ISSUE THREAD

**Issue by Maksaft** [dlyapun/romantic#18]

**Comment by dlyapun** [comment]
Осталось сверстать шаблон

**Comment by misterspelik** [comment]
Димон, а ты хочешь просто сделать отдельную вьюху для контактов и все? Или как страницу и править из админки?

**Comment by dlyapun** [comment]
Там на контакты сложный шаблон выйдет, я так думаю. С картой и формой обратной связи. Поэтому пока лучше пусть будет так.
