### ISSUE TITLE
Умное перенаправление с логина

### ISSUE THREAD

**Issue by dlyapun** [dlyapun/romantic#24]
Сейчас редиректит на блог

**Comment by misterspelik** [comment]
Предлагаю на форме логина записать в сессию страницу, а после успеха средиректить на неё.
Дешево и сердито)

**Comment by dlyapun** [comment]
Можно через get передать просто ссылку. Но там регистрация на Generic display views сделана. Надо разобраться в общем

**Comment by AlexanderPokhylenko** [comment]
Complete
