### ISSUE TITLE
Сверстать страницу "О клубе"

### ISSUE THREAD

**Issue by dlyapun** [dlyapun/romantic#28]
На Зойке висит инфа.

> about.html

**Comment by misterspelik** [comment]
А есть скрин из дизайна или что-то в этом роде? Или надо самим и придумать?

**Comment by dlyapun** [comment]
Только вот это

![screen](https://cloud.githubusercontent.com/assets/2621462/14706299/76323828-07c6-11e6-990c-c5da54588fcb.PNG)
