### ISSUE TITLE
качество фоток на главной странице

### ISSUE THREAD

**Issue by Maksaft** [dlyapun/romantic#31]
![image](https://cloud.githubusercontent.com/assets/15012936/15210507/7dac3124-183f-11e6-8a8b-edaa87756e99.png)

фото выгружаются в плохом качестве

**Comment by dlyapun** [comment]
Это блюр. Посмотри css класс.

**Comment by misterspelik** [comment]
Так давай класс уберем то нафик

**Comment by misterspelik** [comment]
Тьфу, сорян. фильтр конечно же. Можно просто сделать для него другой класс без блюра если этот используется уже где-то.
@dlyapun а ты спецом блюр сделал?

**Comment by dlyapun** [comment]
Да спецом, без блюра смотрится хуже.
